### ISSUE TITLE
Visual glitch due to scroll bar

### ISSUE THREAD

**Issue by delabassee** [tmaiaroto/hugo-redlounge#21]
Vertical scroll bar induce a visual glitch as the page width is slightly reduced (inc. sidebar width).
To see this in action, simply go back and forth between a 'short' page (w/o scroll bar) and a 'long' page (w/ scroll bar).

**Comment by tmaiaroto** [comment]
Can you take a screenshot? What browsers are affected? I'm having a hard time reproducing this (Chrome, OS X). Thanks.

**Comment by delabassee** [comment]
Weird, I'm also on OS X and have the issue on Chrome, Safari and FFox
This short clip (https://www.dropbox.com/s/w3tocb3595l1afu/RedLounge.mp4?dl=0) illustrate the glitch.

**Comment by tmaiaroto** [comment]
I see. This is because of the fluid layout. The columns are sized in percentages and not pixels. So when the scroll bar goes away there's more available space in the viewport so you see this adjustment.

Maybe force the scrollbar to be present all the time if it bothers you. It's just an unfortunate quirk of the internet. I'm open for any clever solutions, but this is typically something I don't worry about.
