### ISSUE TITLE
html5

### ISSUE THREAD

**Issue by xiaobagou** [tmaiaroto/hugo-redlounge#29]
How about html5?

**Comment by tmaiaroto** [comment]
Of course you're welcome to use HTML5 with this theme. Such elements such as ```<article>``` for example. If you'd like to overwrite any template with your own HTML, you certainly can do so. Take a look here for more information: https://gohugo.io/themes/customizing/

Was there a specific issue or concern you had? I'm going to close this because I don't see an issue...But if you feel that there is one, just reply here and we can take a look. Thanks!
